import pandas as pd
import numpy as np
import copy
from perturbation_agents.grad_est_perturb_agent import GradientEstimationPerturbationAgent
from attack_models.BaseAttackerClass import BaseAttackerClass

class GEPerturbAttacker(BaseAttackerClass):
    """
    Gradient Estimation Perturbation Attacker.

    Wrapper class that provides adversarial perturbations to the observations of an environment using a gradient-estimation based perturbation agent.
    Inherit from BaseAttackerClass
    
    Attributes:
        model_name: Identifier for the attacker model
        pickle_file: Default filename
        env: Environment reference
        model: Perturbation model
    """

    def __init__(self, env, agent, **kwargs):
        print(f"[DEBUG] GEPerturbAttacker received agent type: {type(agent)}")
        print(f"[DEBUG] agent.agent type: {type(agent.agent) if hasattr(agent, 'agent') else 'NO .agent attribute!'}")
        self.model_name = "GEPerturbAttacker"
        self.pickle_file = "ge_perturb_attacker.pkl"
        self.env = env

        # Wraps the agent with a gradient-estimation perturbation attacker
        self.model = GradientEstimationPerturbationAgent(self.env.observation_space, agent.agent, **kwargs)


    def perturb(self, obs):
        """
        Apply adversarial perturbation to an observation.

        Args:
            obs: Original environment observation
        
        Returns:
            Perturbed observation generated by the model.
        """
        obs_t = copy.deepcopy(obs) # Works on a copy to avoid mutating the original observation
        obs_perturbed = self.model.perturb(obs_t)
        return obs_perturbed